### ISSUE TITLE
Popups not working correctly

### ISSUE THREAD

**Issue by LennyZ71** [Naimikan/angular-mapboxgl-directive#10]
Able to attach popups from geojson using this object.
```
{
            id: 'metars',
            source: 'metars',
            type: 'circle',
            layout: {
                visibility: 'visible'
            },
            paint: {
                'circle-radius': 5,
                'circle-color': {
                    property: 'fltcat',
                    type: 'categorical',
                    stops: [
                                    ['VFR', '#00b33c'],
                                    ['MVFR', '#0066ff'],
                                    ['IFR', '#ff0000'],
                                    ['LIFR', '#ff00ff']
                                ]
                },
                'circle-opacity': 1.0
            },
            popup: {
                enabled: true,
                onClick: {
                    message: '<div class="metar-popup"><p>${fltcat}</p></div>'
                }
            }
        },
```

Once rendered on map though, the first popup clicked will go away with off click.  But it returns on the next marker that you click for it's popup.  So essentially showing two popups.  The popups also have trouble showing next to their respective marker, when that marker is close to the edge of the map, and marker has a wide div.

Also unable to style the marker popup with css.  Tried setting own class in message popup, and also using generated class.

```
.mapboxgl-popup-content {
    background: 'white';
}

.metar-popu {
    background: 'white';
}
```

See image for explination.

![image](https://cloud.githubusercontent.com/assets/10160563/23267397/43bf79d2-f9b0-11e6-9654-63f51d91ac78.png)

**Comment by Naimikan** [comment]
Hi @LennyZ71!

I updated a version solving this issue. The problem were mousemove event and creation of popups on it. I have to study how I can put popups in mouseover.

Tell me if it worked or If you need something more!

**Comment by Naimikan** [comment]
Oh @LennyZ71, you can change the popup style like:

```css
.mapboxgl-popup-content {
  background-color: #FF0000 !important;
}

.mapboxgl-popup-tip {
  border-top-color: #FF0000 !important;
}
```

**Comment by LennyZ71** [comment]
Thanks, the double pop up issue has been solved.  Am still seeing the issue of markers along the edge.
In image below arrow indicates marker clicked, and you can see where popup renders. Sorry for delay in feedback was on road trip.

![image](https://cloud.githubusercontent.com/assets/10160563/23378020/892e0962-fcf7-11e6-92d0-62e8233b75b9.png)

**Comment by Naimikan** [comment]
Hi @LennyZ71!

Exploring [your example link](https://gom-blocks-and-platforms.firebaseapp.com/#!/map), I saw that you forgot to put `rel="stylesheet"` in mapbox-gl.css and angular-mapboxgl-directive.css link tags. You have to put it and it will work.

```css
<link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/angular-mapboxgl-directive/0.32.3/angular-mapboxgl-directive.min.css">
```

**Comment by LennyZ71** [comment]
Problem solved!   Thanks sorry for oversight there. And Thanks again for getting this directive started.  I'm still processing the changes from using leaflet to gl.
