### ISSUE TITLE
Adding markers

### ISSUE THREAD

**Issue by mm-ns** [Naimikan/angular-mapboxgl-directive#11]
Hi there,

First off thanks for the directive!

I was wondering what's the best approach to add markers? I can see you have glMarkers but I also see others drawing things using the geoJson method.

I tried the following:
`var a = new mapboxgl.LngLat(12.584943, 55.681505);
  var b = new mapboxgl.LngLat(12.584589, 55.681599);
  $scope.glMarkers = [a, b];`

`<mapboxgl track-resize="true" gl-controls="glControls" gl-zoom="mapParam.zoom" gl-style="mapParam.style" gl-center="mapParam.center" gl-markers="glMarkers" ng-if="mapHasLoaded"></mapboxgl>`

But no luck; it says " Error: `LngLatLike` argument must be specified as a LngLat instance, an object {lng: <lng>, lat: <lat>}, or an array of [<lng>, <lat>] ", which is odd because if I inspect it, it does receive the coordinates, but sometimes it also gets `undefined`.

Do you have some examples on how to work with markers via the directive?

**Comment by Naimikan** [comment]
Hi @mm-ns! Thank you very much for use my directive.

I have to complete the documentation. You can create markers using glSources and glLayers directives.

```javascript
$scope.glSources = [
   {
      id: 'markers',
      type: 'geojson',
      data: {
         type: 'FeatureCollection',
         features: [
            {
               type: 'Feature',
               geometry: {
                  type: 'Point',
                  coordinates: [12.584943, 55.681505]
               }
            }, {
               type: 'Feature',
               geometry: {
                  type: 'Point',
                  coordinates: [12.584589, 55.681599]
               }
            }
         ]
      }
   }
];

$scope.glLayers = [
   {
      id: 'markers',
      type: 'circle',
      source: 'markers',
      paint: {
         'circle-radius': 8,
         'circle-color': '#FF620D'
      }
   }
];
```

```html
<mapboxgl
   track-resize="true"
   gl-controls="glControls"
   gl-zoom="mapParam.zoom"
   gl-style="mapParam.style"
   gl-center="mapParam.center"
   gl-sources="glSources"
   gl-layers="glLayers"
   ng-if="mapHasLoaded">
</mapboxgl>
```

Tell me if this worked!

**Comment by mm-ns** [comment]
Hi there!

That's actually what I ended up doing xD Thanks!

**Comment by mm-ns** [comment]
Can this method be used adding custom markers / icons / images?

**Comment by Naimikan** [comment]
Hi!

You can use `glMarkers` directive like:

```javascript
function createElement () {
   var element = document.createElement('div');
   element.style.backgroundImage = 'url(<YOUR_IMAGE>)';

  return element;
}

$scope.glMarkers = [
   {
      coordinates: [12.584943, 55.681505],
      element: createElement()
   }, {
      coordinates: [12.584589, 55.681599],
      element: createElement()
   }
];
```

```html
<mapboxgl
   track-resize="true"
   gl-controls="glControls"
   gl-zoom="mapParam.zoom"
   gl-style="mapParam.style"
   gl-center="mapParam.center"
   gl-markers="glMarkers"
   ng-if="mapHasLoaded">
</mapboxgl>
```

**Comment by mm-ns** [comment]
Cool, Thanks! Appreciate it!

Do you know by any chance if there is any benefit using one method over the other one? Is geojson more performant?

**Comment by Naimikan** [comment]
I dont know if there are any benefits using markers or geojson.
Using markers, you are putting an HTMLElement inside a map canvas, and using geojson, you are drawing on the map.

I hope I've helped.
