### ISSUE TITLE
Clear map controls when back and forth between pages

### ISSUE THREAD

**Issue by mm-ns** [Naimikan/angular-mapboxgl-directive#12]
Hi again,

Everything is running smoothly now, but i'm facing the following problem:

I have a map where I draw a circle via glSources and glLayers and it all works well. However, if I leave my dashboard page and browse to another page on my app, and then I go back to the dashboard, I get the following:

![image](https://cloud.githubusercontent.com/assets/26540637/24109197/34029a76-0d90-11e7-8acb-5cc427bb1b73.png)

Any idea what why? If I stay on dashboard and simply refresh the page, everything works just fine...

**Comment by Naimikan** [comment]
Hi @mm-ns!

What version of mapboxgl and angular-mapboxgl-directive are you using? Can you provide me an example in codepen or in other platform?

**Comment by mm-ns** [comment]
Hi @Naimikan,

I can try to see if I can reproduce that in a plunkr or similar. It looks like some variables, controls, or whatever is left over and not re-initialized. Ill work on making it now...

**Comment by mm-ns** [comment]
Hi there. I made a plunkr here:  https://plnkr.co/edit/HY2tR5MSliZKU9Q3fLB6?p=preview

However I wasn't able to replicate the issue :( I tried to follow my own structure, I tried to simulate ajax requests with timeouts, etc, but no luck :(

I tried to add a console.log() locally on my machine in the angular-mapboxgl-directive in the "checkObjects" method (around line 1739) to print the "eachObject" object, which is where I get a bunch of issues, and when you land on dashboard page for the first time, this is what you see in console.log():

![image](https://cloud.githubusercontent.com/assets/26540637/24146577/8f15c824-0e36-11e7-92f2-b45cf1a9888d.png)

If i browser anywhere else and come back in there, this is what I now see:

![image](https://cloud.githubusercontent.com/assets/26540637/24146589/9d31fef0-0e36-11e7-8a84-83c786db3047.png)

Not sure what to make of this or how to replicate it :'( 

Any idea you may have would be greatly appreciate.

**Comment by mm-ns** [comment]
Oh I just tried to load <script defer src="https://cdnjs.cloudflare.com/ajax/libs/angular-mapboxgl-directive/0.33.0/angular-mapboxgl-directive.js"></script>

0.33 from cdns instead of my local version and I don't experience that issue any longer!!! only have that "TypeError: Cannot read property 'name' of undefined" on angular-mapboxgl-directive.js:746 which is due to the fact that  mapboxgl.FullscreenControl is undefined.

**Comment by mm-ns** [comment]
Also, with the last 0.33 version of the directive, all my map controls are gone (at least they are not displayed) such as geolocator, etc.

**Comment by Naimikan** [comment]
Hi @mm-ns!

I forgot to check if FullscreenControl constructor was undefined. I will update a new version fixing this, sorry!

About your other question, you can inject `mapboxglMapsData` factory and you can use `getMapById`method to get the map instance. Something like:

```html
<div mapbox-gl id="myMap"></div>
```

```javascript
app.controller('MyController', ['$scope', 'mapboxglMapsData', function ($scope, mapboxglMapsData) {
   $scope.$on('mapboxglMap:load', function () {
      var mapInstance = mapboxglMapsData.getMapById('myMap');

      // ...
   });
}]);
```

Tell me if it worked!

**Comment by mm-ns** [comment]
Hi @Naimikan 

No worries! I appreciate your work, it's great.
