### ISSUE TITLE
mapboxgl.util is not longer accessible in the latest release

### ISSUE THREAD

**Issue by mm-ns** [Naimikan/angular-mapboxgl-directive#13]
As per title, wanted to give a heads up that if upgrading to 0.34.0 of Mapbox, mapboxgl.util is not longer accessible in the latest release as per [https://github.com/mapbox/mapbox-gl-js/issues/4393](url)

Not an expert with Mapbox nor the directive, so im not sure yet what this implies in terms of finding the issue. Give wanted to give a heads up :)

**Comment by Naimikan** [comment]
Hi @mm-ns!

I will update the documentation for new CustomControls.

**Comment by Naimikan** [comment]
Hi @mm-ns!

I updated the examples page and wiki for mapboxgl.util deprecation.

Thank you!
