### ISSUE TITLE
Issue with multiple maps

### ISSUE THREAD

**Issue by mm-ns** [Naimikan/angular-mapboxgl-directive#14]
Hi again,

I have an issue where I load multiple independent maps in the same page, and I am having some issues that I can't really pinpoint with both layers and sources.

I was able to replicate a plunkr here: https://plnkr.co/edit/HY2tR5MSliZKU9Q3fLB6?p=preview

Do you have any idea of why that is?

I basically make independent maps in an array and each of the map has its own params, layers, controls and sources. Also I have them in an ng-if so it doesn't try to render the DOM before everything is assigned and has a value.. 

Would love to have your take on it! Thanks!!

**Comment by Naimikan** [comment]
Hi @mm-ns!

I think I know what is the problem. I did all the management factories as Singleton and I have to do as a providers. I'm on it.

Sorry!

**Comment by mm-ns** [comment]
Hi @Naimikan !

No worries! I just thought to mention it in case it went un-noticed ;) I already appreciate the work you do! Thx!

**Comment by Naimikan** [comment]
Hi @mm-ns!

I updated a new version solving your issue!

Tell me if it worked!

**Comment by mm-ns** [comment]
Hey @Naimikan.

thanks a ton, it worked!
