### ISSUE TITLE
Dynamic Markers

### ISSUE THREAD

**Issue by Jogrin** [Naimikan/angular-mapboxgl-directive#15]
Hi! First of all tnx for the great job on the directive.
I'm not be able to add markers after the map initialization.
This is a Plunker with the bug (i used your example from a previous issue, #14 )

[https://plnkr.co/edit/KqlbdOoAbgA9YmABxuMe?p=preview](https://plnkr.co/edit/KqlbdOoAbgA9YmABxuMe?p=preview)

Maybe i'm doing something wrong..

**Comment by Naimikan** [comment]
Hi @Jogrin!

I updated a new version solving the issue!

Tell me if it worked!

**Comment by Jogrin** [comment]
@Naimikan Work like a charm! Tnx!
