### ISSUE TITLE
Add support for Angular 1.6

### ISSUE THREAD

**Issue by idanb11** [Naimikan/angular-mapboxgl-directive#17]
Hi @Naimikan ,

Currently the bower dependencies support only angular 1.5

```
"dependencies": {
  "angular": "~1.5.8"
}
````

But from what I tested, angular-mapboxgl-directive library works well with angular version 1.6.3,
So maybe it is possible to change bower.json dependencies like so: 

```
"dependencies": {
  "angular": ">=1.5 <1.7"
}
````

Thanks.

**Comment by Naimikan** [comment]
Hi @idanb11!

Thank you for the tip!
