### ISSUE TITLE
WMS Layer?

### ISSUE THREAD

**Issue by LennyZ71** [Naimikan/angular-mapboxgl-directive#18]
Naimikan,

I hate asking for help when I'm sure it's somthing I'm doing.  But could you demonstrate the ideal way to add this radar WMS layer?

'https://nowcoast.noaa.gov/arcgis/services/nowcoast/radar_meteo_imagery_nexrad_time/MapServer/WmsServer?service=WMS&request=GetMap&version=1.3.0&layers=1&styles=&format=image%2Fpng&transparent=true&height=481&width=1024&srs=EPSG%3A3857&bbox={bbox-epsg-3857}'

I've tried several different ways to no avail.

Thanks in advance ;)

**Comment by Naimikan** [comment]
Hi @LennyZ71!

I tried to add the radar WMS layer: 

```javascript
$scope.glSources = [
   {
      id: 'wmsSource',
      type: 'raster',
      tiles: [
         'https://nowcoast.noaa.gov/arcgis/services/nowcoast/radar_meteo_imagery_nexrad_time/MapServer/WmsServer?service=WMS&request=GetMap&version=1.3.0&layers=1&styles=&format=image/png&transparent=true&height=481&width=1024&srs=EPSG:3857&bbox={bbox-epsg-3857}'
      ],
      tileSize: 256
   }
];

$scope.glLayers = [
   {
      id: 'wmsLayer',
      source: 'wmsSource',
      type: 'raster',
      paint: {}
   }
];
```
But I got an error: `Parameter 'srs(crs)' has wrong value.`

I don't know what is it, but it seems that parameter srs needs other value.

**Comment by LennyZ71** [comment]
Sorry here is updated URL. Parameter srs is supposed to be crs  It seems to load link for me like that also, but it loads a black layer with no image and covers map, but not other layer I add.

'https://nowcoast.noaa.gov/arcgis/services/nowcoast/radar_meteo_imagery_nexrad_time/MapServer/WmsServer?service=WMS&request=GetMap&version=1.3.0&layers=1&styles=&format=image%2Fpng&transparent=true&height=481&width=1024&crs=EPSG%3A3857&bbox={bbox-epsg-3857}'

**Comment by Naimikan** [comment]
Hi @LennyZ71!

Did you get it to work? I don't know what is the problem. I advise you to open an issue in the repository mapbox-gl.

Sorry!

**Comment by Naimikan** [comment]
Hi @LennyZ71!

I will post an issue en mapbox-gl repository.

**Comment by Naimikan** [comment]
Hi @LennyZ71!

It worked! https://codepen.io/Naimikan/pen/JNYyvd

**Comment by LennyZ71** [comment]
Very nice, I got it working with the glImage directive, but I couldn't get it to update on an interval, and the quality when zooming in didn't seem to render like the WMS does.  I will be swapping it over.  Thanks for the heads up!
