### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by Karttin** [Naimikan/angular-mapboxgl-directive#19]
Hello Naimikan,

Thanks for providing a directive for mapbox.
Will be really useful for new starters if you could post few examples for placing a point, click events, popups etc.

**Comment by Naimikan** [comment]
Hi @Karttin!

Thanks for using my directive! You can see some examples [here](https://naimikan.github.io/angular-mapboxgl-directive/). I'm working on examples page, sorry!

**Comment by SnpDeveloper** [comment]
Thanks for the quick response.

I am trying to replicate the popup functionality  and getting this error.

angular.js:14362 Error: `LngLatLike` argument must be specified as a LngLat instance, an object {lng: <lng>, lat: <lat>}, or an array of [<lng>, <lat>]

Any pointer whats going wrong will help me.

**Comment by Naimikan** [comment]
Hi @SnpDeveloper!

Can you provide me a codepen o something like that, showing how you are doing it?

Thank you!

**Comment by SnpDeveloper** [comment]
Here it is... I tried to use your example itself.
http://plnkr.co/edit/3SFe9S1cwefgbgCzAQmo

I am trying to have a popup for list of points (lat,long) and inside a popup i want a link to take to another page / route url.

I am bit stuck in first step itself, any help appreciated.

Please let me know what i miss.

**Comment by Naimikan** [comment]
Hi @SnpDeveloper!

Yes! There are a bug. I will update a new version solving it!

Thank you!

**Comment by Naimikan** [comment]
Hi @Karttin!

You can find some examples [here](https://naimikan.github.io/angular-mapboxgl-directive/#/)

Thank you!
