### ISSUE TITLE
Default location of the map without fly to effect

### ISSUE THREAD

**Issue by patrikhermansson** [Naimikan/angular-mapboxgl-directive#2]
Hi! I would like the map to center on a certain location directly on load, however when you use the gl-center directive there is always a "fly to" effect. How can this effect be avoided for the first location set. So that it works like mapbox gl default location?

**Comment by patrikhermansson** [comment]
Perfect.

**Comment by Naimikan** [comment]
Hi!

I uploaded a new version solving it. Now "flyTo" only applies when glCenter value is changed.

**Comment by mg1075** [comment]
But how can one access the **real** `flyTo` function as evidenced in this mapbox tutorial?

https://docs.mapbox.com/help/demos/gl-store-locator/step-five.html
view-source:https://docs.mapbox.com/help/demos/gl-store-locator/step-five.html
