### ISSUE TITLE
mapboxglMap:data event gives different object as the event listener function

### ISSUE THREAD

**Issue by idanb11** [Naimikan/angular-mapboxgl-directive#21]
Hi @Naimikan ,

when listening to the 'data' event in mapbox gl SDK - you will receive a (MapDataEvent) object as the function handler input.

But when I use angular-mapboxgl-directive - I get a different object...

This is my scenario:
```
$rootScope.$on('mapboxglMap:data', function(obj) {
  console.log(obj);    
});
```

This output something like:
```
{
name: "mapboxglMap:data", targetScope: m, defaultPrevented: false, currentScope: m, preventDefault: function
}
```

While if I use the directly the mapbox gl SDK like so:
```
var mapInstance = mapboxglMapsData.getMapById('myMap');
mapInstance.on('data', function(obj) {
  console.log(obj)
});
```

I get the correct output - a "MapDataEvent" object:
```
{ 
dataType: "source", sourceDataType: "content", type: "data", target: e, isSourceLoaded: false
}
```
Can you please clarify why this is happening and how can I get the correct MapDataEvent Object?

**Comment by Naimikan** [comment]
Hi @idanb11!

You can get the `MapDataEvent` with the second parameter.

```javascript
$rootScope.$on('mapboxglMap:data', function(angularEvent, mapboxglEvent) {
   //...
});
```

First parameter is the angular event, and the second parameter is the mapboxgl event.

I hope I have helped you, tell me if it worked!

**Comment by idanb11** [comment]
Yes, it worked...

Can you please update the wiki - events page and add this example?
Or tell me how to update the wiki myself?

Thanks.
Idanb11.

**Comment by Naimikan** [comment]
Hi @idanb11!

I have updated the wiki events page. I will update examples page soon.

Thank you!

**Comment by idanb11** [comment]
Thank you @Naimikan
