### ISSUE TITLE
Map does not watch for new features afer initial load

### ISSUE THREAD

**Issue by Genericum** [Naimikan/angular-mapboxgl-directive#23]
Hello Naimikan,

first of all: Thank you for your great work.

Today, I realized a strange behaviour: New features don't get displayed once the map has been painted.

For more information - see this Plunker (based on one of your examples):
https://plnkr.co/edit/qhRTztgEAZAhAijiOgM3

Have a great weekend
Tobi

**Comment by Naimikan** [comment]
Hi @Genericum!

Thank you for use my directive!

Yes, there was an issue, but I fixed it in version 0.34.1. If you change your current version of the directive, it will be solved.

Tell me if it worked!

**Comment by Genericum** [comment]
It worked - thank you.
