### ISSUE TITLE
Language attribute does not work

### ISSUE THREAD

**Issue by Genericum** [Naimikan/angular-mapboxgl-directive#24]
Hello Naimikan,

first of all: Thank you for your great work.

In my opinion the language attribute is not working correctly.

For more information - see this Plunker (based on one of your examples):
https://plnkr.co/edit/paI3ABad1WingeeZiMCR

Maybe something like this peace of code is missing:
if (angular.isDefined(attrs.language)) {
          updateLanguage(map);
}

Thank you & have a great weekend
Tobi

**Comment by Naimikan** [comment]
Hi @Genericum!

Thank you! Yes, there are a bug. I will update a new version solving this soon.

Thank you very much!

**Comment by Naimikan** [comment]
Hi @Genericum!

I have updated a new version solving your problem.

Tell me if it worked!

**Comment by Genericum** [comment]
Hi @Naimikan,

works like a charm - thank you!
