### ISSUE TITLE
Changing style loses glLayers

### ISSUE THREAD

**Issue by chalber** [Naimikan/angular-mapboxgl-directive#26]
Hello,
thanks for tis great library, i have the following issue
i have the style url in a scope object "gl-style=vm.mapboxStyle" but when i change the string the new style gets loaded but all previously loaded layers are gone, how do i retain them?

**Comment by Naimikan** [comment]
Hi @chalber!

Yes, I'm working on that feature. I will update a new version soon.

**Comment by Naimikan** [comment]
Hi @chalber!

I have updated a new version including `persistent` attribute. You have to do something like:

```html
<div mapboxgl gl-sources="glSources" gl-layers="glLayers" persistent="true"></div>
```

With this, if the style changes, glSources and glLayers will recreate with the new style.

Tell me if it worked!
