### ISSUE TITLE
Marker changes its position on zoom

### ISSUE THREAD

**Issue by Mushaqdeen-J** [Naimikan/angular-mapboxgl-directive#28]
Hi, 
     Thanks for this directive, it was very useful for me. I have successfully integrated this in one of my project . But the icon(marker) that I placed in map is not fixed while zoom in or out. The marker is changes its position while zoom. I am using angular-mapboxgl-directive 0.38.0 2017-07-11.

**Comment by Naimikan** [comment]
HI @Mushaqdeen-J!

Thank you, can you provide me an example?

**Comment by Mushaqdeen-J** [comment]
http://demo.empower-erp.com:88/sms-screen/index.html#/details/5001

**Comment by Naimikan** [comment]
Hi @Mushaqdeen-J!

Well, I think the problem is marker object. In Mapbox GL, the (0, 0) point in a marker is top-left corner, not the center of the image. Then, when you create a marker, you have to do something like:

```javascript
$scope.markers = [
   {
      coordinates: [lng, lat],
      element: DOMElement, // ex: div with image 30x30px
      options: {
         offset:[-15, -15] // this values are width/2 and height/2 of image dimensions
      }
   }
];
```

Tell me if it worked and if i can help you with something more!

**Comment by Naimikan** [comment]
Hi @Mushaqdeen-J!

Did you solve the problem?

**Comment by Mushaqdeen-J** [comment]
Hi
`options: {
         offset:[-15, -15] // this values are width/2 and height/2 of image dimensions
      }`
fixed the problem, Now its working fine. Now I want to fit two markers in a view bound. Is there any directive to do that.

**Comment by Naimikan** [comment]
Hi @Mushaqdeen-J!

I think that directive you are looking for is glMaxBounds, but I don't understand what you want to do.

**Comment by Mushaqdeen-J** [comment]
Oh sorry, what I want is I set my zoom as 12 and I placed two markers in my map but the two markers are not in my zoom level anyway I want to change my zoom level to fit the markers in my zoom level

**Comment by Naimikan** [comment]
Well, I think if you use glMaxBounds directive, you can do it.

I hope I have helped you.

**Comment by Naimikan** [comment]
Oh, sorry, I'm working on example page.

You can find [here](https://github.com/Naimikan/angular-mapboxgl-directive/wiki/Directives#glmaxbounds-lnglatboundslike) my (incomplete) wiki, or [here](https://www.mapbox.com/mapbox-gl-js/example/restrict-bounds/) for mapbox-gl example.

**Comment by Mushaqdeen-J** [comment]
No luck check the below link
http://demo.empower-erp.com:88/sms-screen/index.html#/details/5014

**Comment by Naimikan** [comment]
Hi @Mushaqdeen-J!

Did you solve the problem?
