### ISSUE TITLE
Setting language attribute when using custom style

### ISSUE THREAD

**Issue by ExaltedJim** [Naimikan/angular-mapboxgl-directive#29]
Hi,

Question - should the language attribute work when applying a custom style to mapbox?

It seems to work when there is no style applied, but as soon as I apply my custom style with the gl-style directive the language reverts back to English.

Thanks.

**Comment by Naimikan** [comment]
Hi @ExaltedJim!

I think you have to define your languages by style, but I don't know exactly. Sorry!
