### ISSUE TITLE
Directive can't be found when using browserify.

### ISSUE THREAD

**Issue by patrikhermansson** [Naimikan/angular-mapboxgl-directive#3]
Great work on this project! I've been using it in a project that I am now moving over to browserify and it doesn't seem to work. Maybe I'm doing something wrong but first installing it with 'npm install' and then including it in my angular app with 'require' results in an error saying that 'mapboxgl-directive' doesn't exist and that my angular app therefore can't be loaded. Although the code is includes like it should with 'require'.

**Comment by Naimikan** [comment]
Hello! Thank you for using my project.

I have not tried the directive with the browserify and I do not know what happens. I'll try it and let you know the results.

**Comment by Naimikan** [comment]
Hi @patrikhermansson!

I've updated the directive and added a new grunt task for browserify. I couldn't prove it, tell me if it works.
