### ISSUE TITLE
fitbounds 

### ISSUE THREAD

**Issue by sK0pe** [Naimikan/angular-mapboxgl-directive#30]
Hi @Naimikan, I've been messing around with moving to Angular using your helpful directive however the mapbox-gl "fitbounds" function is one that I can't seem to access or maybe it's missing, not really sure as to how to get to this functionality.  I found it very useful when using regular Leaflet and Mapbox-Gl.

**Comment by Naimikan** [comment]
Hi @sK0pe!

You can access to `mapboxgl` instance injecting `mapboxglMapsData` service, like this:

```html
<div mapboxgl id="myMap"></div>
```

```javascript
app.controller('MyController', ['mapboxglMapsData', '$scope', function (mapboxglMapsData, $scope) {
   $scope.$on('mapboxglMap:load', function (event, mapboxglMapEvent) {
      $scope.mapInstance = mapboxglMapsData.getMapById('myMap');

      // Now, you can use fitbounds function with $scope.mapInstance
   });
}]);
```

Tell me if it worked!

**Comment by sK0pe** [comment]
Hi @Naimikan sorry for the late reply, I had to move onto some other projects.
I came back to my mapping portion and your code worked great!
Sorry for the noobish question but I've ended up at AngularJS and Javascript project coming from an Angular / Typescript path, so your powerful directive didn't make complete sense initially.
