### ISSUE TITLE
mapbox-gl-draw instance

### ISSUE THREAD

**Issue by sprattek** [Naimikan/angular-mapboxgl-directive#32]
Hey, thanks for a great directive, I'm trying to extend it a bit with some custom functions which I need. I've already added [circle drawing tool](https://github.com/mblomdahl/mapbox-gl-circle) which works perfect.

Now I would need some kind of floorplan positioning tool, currently I'm adding image layer with floorplan and I would like to add drawing tool polygon with same coordinates onto that and then redraw image in draw.update event. However I can't figure out how to get drawing tool instance in the directive so I can add polygon programatically. So I would need to do something like that straight in directive:

```javascript
var feature = {
  id: 'draw-'+elementId,
  type: 'Feature',
  properties: {},
  geometry: { type: 'Polygon', coordinates: cornerPoints }
};
var featureIds = draw.add(feature);
```

I've already tried to init whole drawing plugin in directive instead of enabling drawing via glControls like that:

```javascript
//Create a Draw control
var draw = new MapboxDraw();

// Add the Draw control to your map
map.addControl(draw);

var feature = {
        id: 'draw-'+elementId,
        type: 'Feature',
        properties: {},
        geometry: { type: 'Polygon', coordinates: cornerPoints }
};
var featureIds = draw.add(feature);
```

but it's working a bit weird as polygon is not visible initially but after clicking somewhere on map it appears. So question, is it possible to get draw instance somehow and add polygon programatically? 

Any advices are welcome, thanks.

**Comment by Naimikan** [comment]
Hi @sprattek!

Currently, it's not posible to get the draw instance, but I will update a new version including this feature.

Thank you!

**Comment by sprattek** [comment]
Sounds great, thanks for a feedback.

**Comment by Naimikan** [comment]
Hi @sprattek!

I have updated a new version, adding `mapboxglMap:controlsRendered` event. You can get control instance like:

```javascript
$scope.$on('mapboxglMap:controlsRendered', function (event, controlsRendered) {
   if (controlsRendered.draw) {
      var mapboxglDrawInstance = controlsRendered.draw.control;
   }
});
```

Tell me if it worked!

**Comment by sprattek** [comment]
Wow that was fast pal and it's working great, thank you. 

Unfortunately I'm having same issue while added polygon is not visible until clicking somewhere on map and I realized that it's probably because it's not added after map is loaded in "on load" event. In this [jsfiddle](https://jsfiddle.net/opf9z4ft/10/) it's working fine while I'm adding draw in load event but if it's moved outside, polygon is not visible until map click. 

I've already tried to use 
```javascript
$scope.$on('mapboxglMap:load', function () {

});
```

but it doesn't seems to help, do you have any idea how to add draw properly after map is loaded?

Thanks

**Comment by Naimikan** [comment]
Hi @sprattek!

I think you have to wait until map is loaded to add some features. But I could add a new attribute for draw control to add default features.

Thank you!

**Comment by sprattek** [comment]
Hi @Naimikan,

thank you for response, I know that I've to wait for map to be loaded and I've tried to use 'mapboxglMap:load' for that purpose but as I said it doesn't seem to help so I was just wondering if there is maybe some other listener or maybe you have some idea how to wait for map loaded event. Anyway no probs if nothing crossed your mind, keep up good work and thank you again.

**Comment by sprattek** [comment]
In case someone will be looking for a working workaround, this is something what's working for me:

```javascript
var drawAdded = false;

this.mapInstance.on('render', function(data) {
  if(data.target.loaded() && !drawAdded) {
    var featureIds = mapboxglDrawInstance.add(feature);
    mapboxglDrawInstance.changeMode('direct_select', {
      featureId: featureIds[0]
    });
    drawAdded = true;
  }
});
```

**Comment by Naimikan** [comment]
Hi @sprattek!

I have added a new feature in glControls draw. You can initialize features in draw instance like:

```javascript
scope.glControls = {
   draw: {
      enabled: true,
      features: <YOUR_ARRAY_OF_FEATURES>
   }
};
```

Tell me if it worked!

**Comment by jfan0888** [comment]
Hi @Naimikan!

Thanks for creating this directive. Currently I am trying to save and load something which I drawn by tool. Could you kindly assist me? I attached a screenshot to help your understanding.

**Comment by Naimikan** [comment]
Hi @jfan0888!

Can you create a new issue with this problem and explain it? Thank you!

**Comment by jfan0888** [comment]
Hi @Naimikan!

Thanks for your response. I will do.
