### ISSUE TITLE
Question: Understanding today's limitations?

### ISSUE THREAD

**Issue by that1guy** [Naimikan/angular-mapboxgl-directive#36]
Hi @Naimikan,

We have a production application that leverages https://github.com/angular-ui/ui-leaflet, which is a fork of https://github.com/tombatossals/angular-leaflet-directive.  On top of `angular-ui leaflet` we use https://github.com/Leaflet/Leaflet.markercluster for marker clustering, and https://github.com/Leaflet/Leaflet.label for advanced labeling needs.  Lastly, we have a huge implementation that overlays thousands of geoJSON shapes over the mapbox tiles so users can perform geospatial queries.

My question is, can your directive do any form of marker clustering, advanced marker labeling, and are there geoJSON click listeners so I can do things that change the colors of geoJSON shapes to indicated the user selected it?  Thanks for clarification here.

We're working hard to find a solution that combines mapboxGl + Angular1 + plus all the features our production application needs.

**Comment by Naimikan** [comment]
Hi @that1guy!

Hmmm... let me see if I can do a test with clustering and I tell you.

Thank you!
