### ISSUE TITLE
Edit Geofence once rendered on mapbox

### ISSUE THREAD

**Issue by aakashbehal** [Naimikan/angular-mapboxgl-directive#37]
Hi, 
love your directives, helped me a lot.
However i am stuck in editing a shape created through draw method.
This is when i get latlong data from the server which i created previously and saved to the server, i was able to render geofence on map with 
```
<div mapboxgl
      gl-controls="glControls"
      gl-zoom="{ value: 10 }"
      gl-center="{ lat: 38.90579608933237, lng:  -77.12973173932926}"
      gl-sources="glSources"
      gl-layers="glLayers">
    </div>
```

but not able to edit this shape.
Use Case - GEOFENCE

**Comment by Naimikan** [comment]
Hi @aakashbehal!

I have added a new attribute to glControls draw control. You can assign features to draw control and then edit them.

```javascript
// First, add draw control to glControls

scope.glControls = {
   draw: {
      enabled: true,
      features: <YOUR_ARRAY_OF_FEATURES>
   }
};
```

```html
<div mapboxgl gl-controls="glControls" ... ></div>
```

I will update an example soon.

Tell me if it worked!
