### ISSUE TITLE
Navigation control does not work

### ISSUE THREAD

**Issue by BohdanKorinnyi** [Naimikan/angular-mapboxgl-directive#38]
Hi, I'm trying to add navigation control to my map but it doesn't appear. I use code from [example](https://naimikan.github.io/angular-mapboxgl-directive/#/examples/show_navigation_control).
Also I tried to run other examples from control section and it also didn't work.
What is wrong? Why does it not work? Example in [jsfiddle](https://jsfiddle.net/zkba7npd/)
![image](https://user-images.githubusercontent.com/8822555/34479897-e04cfb60-efb1-11e7-9492-e76944cefd3e.png)
Thanks!

**Comment by Naimikan** [comment]
Hi @BohdanKorinnyi!

I think that the problem is <link> tag. I forgot to put rel="stylesheet" in <link> tags.

Tell me if it worked!

**Comment by BohdanKorinnyi** [comment]
Hi @Naimikan!
I changed div to `<div mapboxgl gl-controls="glControls" rel="stylesheet"></div>`. It still doesn't work.

**Comment by Naimikan** [comment]
No @BohdanKorinnyi!

You have to put rel="stylesheet" in <link> tags:

```html
<link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/v0.39.1/mapbox-gl.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/angular-mapboxgl-directive/0.39.0/angular-mapboxgl-directive.min.css">
```

**Comment by BohdanKorinnyi** [comment]
It works!
Thanks a lot @Naimikan! :raised_hands:
