### ISSUE TITLE
Invalid source ID

### ISSUE THREAD

**Issue by DarrenBangsund** [Naimikan/angular-mapboxgl-directive#39]
I've been staring at this one trying to figure it out for a while now and can't seem to figure it out, I apologize if it's something simple that I'm missing! I'm trying to add a source from a mapbox url through the gl-sources directive, so I'm feeding an [Object] type in:
![image](https://user-images.githubusercontent.com/11287980/34683946-69495d46-f458-11e7-926b-9f26628c2b38.png)

And receive the error:
```
Error: Invalid source ID
    at SourcesManager.removeSourceById (angular-mapboxgl-directive.js:1360)
```

So I try to include an id in the source definition:
![image](https://user-images.githubusercontent.com/11287980/34684072-c4aef1d2-f458-11e7-9a22-a514ba0fe2b6.png)

And receive a new error:
```
TypeError: currentSource.setData is not a function
    at SourcesManager.updateSourceByObject (angular-mapboxgl-directive.js:1414)
```

I'm scratching my head over this one can't seem to figure it out.
Thanks!

**Comment by Naimikan** [comment]
Hi @DarrenBangsund!

Thank you for use my directive. Could you provide me a codepen or something like that?

Thank you.
