### ISSUE TITLE
Markers lose its position during scroll

### ISSUE THREAD

**Issue by BohdanKorinnyi** [Naimikan/angular-mapboxgl-directive#40]
Hi! 
In the beginning thanks for the great directive :+1: 

I have a trouble when scrolling a map with markers. Each markers lose its position in the moment of scrolling and get right position after finishing of the process.

![image](https://user-images.githubusercontent.com/8822555/34724146-7f7c8d1a-f555-11e7-944f-32b171eb639c.png)
1. Before scrolling
2. In the moment of scrolling
3. After scrolling

Do you have any idea how can I fix it?

I use the following code to create markers:
```
$scope.glMarkers = [
        {
            coordinates: [18.080007, 59.332315],
            element: createMarker('el0', 'fa fa-map-marker fa-2x red')
        }
];
function createMarker(id, classNames) {
        let element = document.createElement('div');
        element.className = 'marker';
        element.innerHTML = '<i id="' + id + '" class="' + classNames + '"></i>';
        return element;
    }
```

**Comment by Naimikan** [comment]
Hi @BohdanKorinnyi!

Can you provide me a codepen?

Thank you!

**Comment by BohdanKorinnyi** [comment]
Hi @Naimikan !
I use this icon [here](http://fontawesome.io/icon/map-marker/).

**Comment by BohdanKorinnyi** [comment]
@Naimikan Do you have any idea how to fix this wrong behavior?

**Comment by Naimikan** [comment]
Hi @BohdanKorinnyi 

Can you do an example with codepen to check the problem?

Thank you

**Comment by BohdanKorinnyi** [comment]
Hi @Naimikan 
I created a repository with example and you can take a look here: https://bohdankorinnyi.github.io/mapbox-gl-angular/

Thank you

**Comment by Naimikan** [comment]
Hi @BohdanKorinnyi!

I think the problem is from Mapbox GL library, and I don't know how to solve it, but, If you want, you can use circle geojson instead marker.

```javascript
$scope.glSources = [
          {
            id: 'marker',
            type: 'geojson',
            data: {
              type: 'Feature',
              geometry: {
                type: 'Point',
                coordinates: [18.061287, 59.346935]
              }
            }
          }
];

$scope.glLayers = [
   {
      id: 'marker',
      source: 'marker',
      type: 'circle',
      paint: {
          'circle-radius': 23,
          'circle-color': '#FF1A47',
          'circle-opacity': 0.7,
          'circle-stroke-width': 2,
          'circle-stroke-color': '#FF0033'
      }
   }
];
```

Sorry!
