### ISSUE TITLE
How can I use an image as an icon-image for the 'unclustered-point' layer?

### ISSUE THREAD

**Issue by renanasofia** [Naimikan/angular-mapboxgl-directive#41]

**Comment by Naimikan** [comment]
Hi @renanasofia!

I'm not sure how to do that, let me think about it.

I think that you have to change the layer type to symbol and use your custom sprite file. I hope this link helps you https://stackoverflow.com/questions/42322746/adding-url-images-to-mapbox-gl-js-layers
