### ISSUE TITLE
Map doesn't handle data changes after any events

### ISSUE THREAD

**Issue by BohdanKorinnyi** [Naimikan/angular-mapboxgl-directive#42]
Hi @Naimikan !

I have a map on my page. It has default center.

    $scope.glCenter = { lat: 45.53, lng: -73.58 };

I added simple event listener to my map in order to change map's center to another coordinates after click by map. It looks like:

    $scope.$on('mapboxglMap:click', function (event, events) {
        $scope.glCenter = { lat: 45.53, lng: -72.58 };
    });

After I clicked by map it doesn't change the center.

I added `ng-keydown` to my body tag `ng-keydown="keydown($event)"`.

    $scope.keydown = function(event) {
        console.log('just print log');
    }

I can change center of the map doing the following steps:
1. Click by map
2. Press any key
3. Center is changing

I expect other behaviour:
1. Click by map
2. Center is changing

Could you help me?

Thank you!

[CODE](https://github.com/BohdanKorinnyi/mapboxgl-click-event/blob/master/index.html) [DEMO](https://bohdankorinnyi.github.io/mapboxgl-click-event/index.html)

**Comment by Naimikan** [comment]
Hi @BohdanKorinnyi!

The problem is the angular scope, you have to do an $apply on the $scope:

```javascript
$scope.$on('mapboxglMap:click', function (event, events) {
   $scope.$apply(function () {
      $scope.glCenter = { lat: 45.53, lng: -72.58 };
   });
});
```

Tell me if it worked!

**Comment by BohdanKorinnyi** [comment]
Hi @Naimikan !

Thank you! It works well !
