### ISSUE TITLE
Question: Clean source and layer

### ISSUE THREAD

**Issue by BohdanKorinnyi** [Naimikan/angular-mapboxgl-directive#46]
Hi @Naimikan !
I try to remove all layers from from the map but in some reason it doesn't work.

I have the following sources

```
$scope.glSource
```

In order to remove all source I do:

```
$scope.glSource = []
```
After that I try to add a source with id that was in `$scope.glSource` before removing I receive an error because the souce already exists with such id.

How can I remove source/layer correctly?

**Comment by Naimikan** [comment]
Hi @BohdanKorinnyi!

Could you provide me a codepen with an example?

Thank you!

**Comment by Naimikan** [comment]
Hi @BohdanKorinnyi!

You can remove sources and layers with:
```javascript
$scope.glSources = []; // Sources
$scope.glLayers = []; // Layers
```
But remember, you have to remove sources and layers to clean all correctly.

Tell me if it worked!

**Comment by BohdanKorinnyi** [comment]
@Naimikan Thank you! It works for me!
