### ISSUE TITLE
Request: Add git tag with each version

### ISSUE THREAD

**Issue by K1N5L4Y3R** [Naimikan/angular-mapboxgl-directive#5]
It would be great if whenever the project version changes (i.e. version in bower.json), the repository was tagged, so that navigation was easier and external tools could handle this package's versioning as well (in my case, I want to use it via [Rails Assets](https://rails-assets.org) but the package cannot be added unless it includes tags for versions [please see https://github.com/FezVrasta/bootstrap-material-design/issues/57 as an example]).

Maybe tags aren't needed for every single patch but maybe minor and major version changes should be tagged IMO.

**Comment by Naimikan** [comment]
Thank you @K1N5L4Y3R, I'm on it!

**Comment by Naimikan** [comment]
Hi @K1N5L4Y3R, I tagged the version 0.30.3 and I think I added the package to Rails Assets. Tell me if you need something more.

Thank you very much!

**Comment by K1N5L4Y3R** [comment]
That's all I needed. Gracias!
