### ISSUE TITLE
Question: Is there a simple way to get a reference to the underlying map?

### ISSUE THREAD

**Issue by vomc** [Naimikan/angular-mapboxgl-directive#52]
Hi,

Haven't spent too much time digging around the src but looking through the examples, I was wondering if there is a way to get a reference (to be able to call methods) on the underlying mapboxGL object in a controller. 

I can set zoom, center, etc as properties in my controller and pass those to the directive according to the examples that are on the site but what if I wanted to get a reference to the map in my controller? Is that possible?

Thank you
Best
- J

**Comment by Naimikan** [comment]
Hi @vomc!

You can get the mapboxGL object using `load` event:

```html
<div mapboxgl id="myMap"></div>
```

```javascript
app.controller('MyController', ['mapboxglMapsData', function (mapboxglMapsData) {
   $scope.$on('mapboxglMap:load', function (event, mapboxglMapEvent) {
      $scope.mapInstance = mapboxglMapsData.getMapById('myMap');
   });
}]);
```

I hope I've helped you!

**Comment by vomc** [comment]
Thank you so much! That is very helpful.

**Comment by siddmegadeth** [comment]
Is there is a way to pass data into direction control from controller .
i have 2 coordinates. 
one is origin and another is destination.
How can i pass data to direction control.

Quick help would be apprecialted
