### ISSUE TITLE
Invalid max bounds

### ISSUE THREAD

**Issue by K1N5L4Y3R** [Naimikan/angular-mapboxgl-directive#6]
Im trying to use the `glMaxBounds` directive but getting an `Invalid max bounds` error.

I face this error both while trying to use it as per the wiki
`<mapboxgl gl-max-bounds="[[-73.9876, 40.7661], [-73.9397, 40.8002]]"></mapboxgl>`
, and with the controller scope
`<mapboxgl gl-max-bounds="bounds"></mapboxgl>`
`$scope.bounds = [[-73.9876, 40.7661], [-73.9397, 40.8002]]`

When debugging it looks like `maxBounds` is set to `undefined` in `mapboxGlMaxBoundsDirectiveLink()`.

![image](https://cloud.githubusercontent.com/assets/2091837/22811568/35c4048e-ef05-11e6-89e0-a95dbef51116.png)

Do you have a working example for this directive?

---

Off-topic: Is there a way to do what `map.fitBounds()` does using this project? If not, how could I get an instance of the map on my controller?

**Comment by Naimikan** [comment]
Hi @K1N5L4Y3R, I solved the problem. I forgot to insert the watcher for glMaxBounds directive.

About your off-topic, you can use `mapboxglMapsData` factory. You have to do something like:

```html
<mapbox-gl id="myMap"></mapbox-gl>
```

```javascript
angular.controller('MyController', ['mapboxglMapsData', function (mapboxglMapsData) {
   var myMap = mapboxglMapsData.getMapById("myMap");
   //....
}]);
```

Tell me if you need something more!

Thank you very much!

**Comment by K1N5L4Y3R** [comment]
Wow, that was quick. Keep up the good work! Thanks
