### ISSUE TITLE
Popups

### ISSUE THREAD

**Issue by patrikhermansson** [Naimikan/angular-mapboxgl-directive#7]
Hi!
I'm having problems with the popup api. Very easy to get popups to display by adding the 'popup' object to 'glLayers', however I cannot find a way to add a dynamic message or run a callback function on click? The 'message' attribute only allows for string.

For example: I send certain properties for each feature in my GeoJSON, such as an id. I'd like to use this id to fetch more data on the feature and display that in the popup. Have I missed something or is this just not possible right now?

Also: Would it be possible to trigger popups with hover?

**Comment by Naimikan** [comment]
Hi @patrikhermansson!

The message attribute accept directives. I think you want to do something like:

```javascript
$scope.glSources = {
   //...
   data: {
      type: 'Feature',
      geometry: { //... },
      properties: {
         id: 'myParameter',
         param: 'myOtherParam'
      }
   }
   //...
};

$scope.glLayers = {
   //...
   popup: {
      enabled: true,
      // You can pass a directive
      message: '<my-message-directive my-attribute="${id}"></my-message-directive>',
      // Or you can pass HTML with ng-click directive passing attributes
      message: '<div class="..." ng-click="myClickFunction(${id}, ${param});"></div>',
      getScope: function () {
         return $scope;
      }
   }
   //...
};

$scope.myClickFunction = function (id, otherParam) {
   // Here, you have the id and you can make an ajax call or what you want
};
```
I hope I have helped you, tell me if it works or if you need something more!

**Comment by patrikhermansson** [comment]
Thank you very much! Works perfectly. Maybe put the attribute part in the documentation? :)

**Comment by Naimikan** [comment]
@patrikhermansson yes, I have to complete the documentation 😅
