### ISSUE TITLE
can I use this module with Angular 2 ?

### ISSUE THREAD

**Issue by AsmaGargouri** [Naimikan/angular-mapboxgl-directive#8]
I am working in an Angular 2 project and wish to integrate mapbox. Is it possibile to use this directive?

**Comment by Naimikan** [comment]
Hi @AsmaGargouri! I haven't test the module in a Angular 2 project, and I don't know if it's possible. But you can use [angular2-mapboxg](https://github.com/kuflink/angular2-mapbox) by @kuflink.
Or maybe this [plnkr](https://plnkr.co/edit/M4m4aZMNr3yc7TgMD9Ko?p=preview) could help you.

I hope I've helped you.

**Comment by AsmaGargouri** [comment]
@Naimikan thanks for your answer. Well, actually I had a problem with  angular2-mapboxgl by @kuflink. I'll try to use something else. maybe the javascript lib !

**Comment by Naimikan** [comment]
Sorry @AsmaGargouri! Porting this directive from 1.x to 2.x is in my roadmap. I will do it once everything that Mapbox GL offers is implemented in my 1.x directive.

**Comment by viztastic** [comment]
@Naimikan Any news on when you think you'll be able to port it from 1 to 2.x?

**Comment by Naimikan** [comment]
Hi @viztastic!

I was very busy and I do not know when I can have a stable version. Sorry!
